### ISSUE TITLE
Spacing of panel popup menu

### ISSUE THREAD

**Issue by robot-ave** [Fausto-Korpsvart/Material-GTK-Themes#2]
Loving this theme so far, but having a small issue with the panel right-click menu (first screenshot below). The items in the list are kind of short and close together, making it difficult to select a specific option quickly...

Any possibility of giving each menu item some extra padding, similar to screenshot 2?

![Screenshot from 2022-05-22 17-42-08](https://user-images.githubusercontent.com/31192190/169719264-b5932aa4-5343-4122-b2ad-7ffa9e451c48.png)
![Screenshot from 2022-05-22 17-44-34](https://user-images.githubusercontent.com/31192190/169719265-52ca3cfb-a91e-42cb-9513-127bcac3752f.png)

Thanks :-)

**Comment by Fausto-Korpsvart** [comment]
> Loving this theme so far, but having a small issue with the panel right-click menu (first screenshot below). The items in the list are kind of short and close together, making it difficult to select a specific option quickly...
> 
> Any possibility of giving each menu item some extra padding, similar to screenshot 2?
> 
> ![Screenshot from 2022-05-22 17-42-08](https://user-images.githubusercontent.com/31192190/169719264-b5932aa4-5343-4122-b2ad-7ffa9e451c48.png) ![Screenshot from 2022-05-22 17-44-34](https://user-images.githubusercontent.com/31192190/169719265-52ca3cfb-a91e-42cb-9513-127bcac3752f.png)
> 
> Thanks :-)

Hi, @ThatGrimshaw, I'm going to check to fix the problem, but I'm curious, what version of Gnome are you using? because I've tried on Manjaro Gnome with all the latest updates and Fedora, which is my main OS, and I'm not seeing this problem.

Thanks for reporting and for the support. };-]

**Comment by robot-ave** [comment]
After taking another look, it seems that my gnome-shell-theme.gresource file got corrupted which was causing the issue. Fixed after reinstalling gdm and `dconf reset -f /org/gnome`

Looks great now:
![Screenshot from 2022-05-23 09-35-20](https://user-images.githubusercontent.com/31192190/169843988-5da8e823-c0ef-42d4-bea4-67422f629c8f.png)

So, disregard me -- user error :,-)

**Comment by Fausto-Korpsvart** [comment]
> After taking another look, it seems that my gnome-shell-theme.gresource file got corrupted which was causing the issue. Fixed after reinstalling gdm and `dconf reset -f /org/gnome`
> 
> Looks great now: ![Screenshot from 2022-05-23 09-35-20](https://user-images.githubusercontent.com/31192190/169843988-5da8e823-c0ef-42d4-bea4-67422f629c8f.png)
> 
> So, disregard me -- user error :,-)

Great, thanks for reviewing and clarifying, as soon as I can, I will make an update that resolves other small errors. };-]
